#!/bin/bash
#
# AURORA Installation Script
# Adaptive Unified Runtime & Orchestration for Resource Acceleration
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default settings
PREFIX="/opt/aurora"
INSTALL_KERNEL=false
TUNE_SYSTEM=false
BUILD_TYPE="release"

# Print banner
print_banner() {
    echo -e "${BLUE}"
    cat << "EOF"
    ╔═══════════════════════════════════════════════════════════╗
    ║                                                           ║
    ║     █████╗ ██╗   ██╗██████╗  ██████╗ ██████╗  █████╗     ║
    ║    ██╔══██╗██║   ██║██╔══██╗██╔═══██╗██╔══██╗██╔══██╗    ║
    ║    ███████║██║   ██║██████╔╝██║   ██║██████╔╝███████║    ║
    ║    ██╔══██║██║   ██║██╔══██╗██║   ██║██╔══██╗██╔══██║    ║
    ║    ██║  ██║╚██████╔╝██║  ██║╚██████╔╝██║  ██║██║  ██║    ║
    ║    ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝    ║
    ║                                                           ║
    ║    Adaptive Unified Runtime & Orchestration               ║
    ║    for Resource Acceleration                              ║
    ╚═══════════════════════════════════════════════════════════╝
EOF
    echo -e "${NC}"
}

# Print usage
usage() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  -p, --prefix DIR       Installation prefix (default: /opt/aurora)"
    echo "  -k, --kernel           Install kernel modules"
    echo "  -t, --tune             Tune system for optimal performance"
    echo "  -d, --debug            Build in debug mode"
    echo "  -h, --help             Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0                     # Install to /opt/aurora"
    echo "  $0 -p ~/.local/aurora  # Install to home directory"
    echo "  $0 -k -t               # Install with kernel modules and tuning"
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -p|--prefix)
            PREFIX="$2"
            shift 2
            ;;
        -k|--kernel)
            INSTALL_KERNEL=true
            shift
            ;;
        -t|--tune)
            TUNE_SYSTEM=true
            shift
            ;;
        -d|--debug)
            BUILD_TYPE="debug"
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            usage
            exit 1
            ;;
    esac
done

# Check prerequisites
check_prerequisites() {
    echo -e "${BLUE}Checking prerequisites...${NC}"
    
    # Check for Rust
    if ! command -v rustc &> /dev/null; then
        echo -e "${RED}Rust is not installed. Please install Rust first:${NC}"
        echo "  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
        exit 1
    fi
    
    # Check Rust version
    RUST_VERSION=$(rustc --version | cut -d' ' -f2)
    echo -e "  ${GREEN}✓${NC} Rust $RUST_VERSION"
    
    # Check for Cargo
    if ! command -v cargo &> /dev/null; then
        echo -e "${RED}Cargo is not installed${NC}"
        exit 1
    fi
    echo -e "  ${GREEN}✓${NC} Cargo"
    
    # Check for required libraries
    if command -v pkg-config &> /dev/null; then
        echo -e "  ${GREEN}✓${NC} pkg-config"
    fi
    
    echo ""
}

# Build AURORA
build_aurora() {
    echo -e "${BLUE}Building AURORA...${NC}"
    
    cd "$(dirname "$0")/.."
    
    if [ "$BUILD_TYPE" = "release" ]; then
        echo "  Building in release mode..."
        cargo build --release
    else
        echo "  Building in debug mode..."
        cargo build
    fi
    
    echo -e "  ${GREEN}✓${NC} Build complete"
    echo ""
}

# Install files
install_files() {
    echo -e "${BLUE}Installing AURORA to $PREFIX...${NC}"
    
    # Create directories
    echo "  Creating directories..."
    mkdir -p "$PREFIX"/{bin,lib,etc,share/aurora,var/cache/aurora}
    
    # Install binary
    echo "  Installing aurora binary..."
    if [ "$BUILD_TYPE" = "release" ]; then
        cp target/release/aurora "$PREFIX/bin/"
    else
        cp target/debug/aurora "$PREFIX/bin/"
    fi
    chmod +x "$PREFIX/bin/aurora"
    
    # Install libraries
    echo "  Installing libraries..."
    if [ "$BUILD_TYPE" = "release" ]; then
        cp target/release/*.so "$PREFIX/lib/" 2>/dev/null || true
        cp target/release/*.a "$PREFIX/lib/" 2>/dev/null || true
    else
        cp target/debug/*.so "$PREFIX/lib/" 2>/dev/null || true
        cp target/debug/*.a "$PREFIX/lib/" 2>/dev/null || true
    fi
    
    # Install configuration
    echo "  Installing configuration..."
    cat > "$PREFIX/etc/aurora.conf" << 'EOF'
# AURORA Configuration File
# Generated by install.sh

[runtime]
# Thread pool size (auto = number of physical cores)
thread_pool_size = auto

# Memory pool size in MB
memory_pool_size = 1024

# Enable work-stealing scheduler
work_stealing = true

[performance]
# Use HugePages for large allocations
use_hugepages = true

# Use NUMA-aware memory allocation
use_numa = true

# CPU frequency governor (performance, powersave, ondemand)
cpu_governor = performance

# Enable CPU affinity
cpu_affinity = true

[gpu]
# Enable CUDA backend
enable_cuda = true

# Enable ROCm backend
enable_rocm = true

# Enable Vulkan backend
enable_vulkan = true

# Enable OpenCL backend
enable_opencl = false

[profiling]
# Enable performance profiling
enabled = true

# Profile cache path
profile_cache = /var/cache/aurora/profile.toml

# Auto-tune based on execution history
adaptive_tuning = true

[logging]
# Log level (error, warn, info, debug, trace)
level = info

# Log file path (optional)
# log_file = /var/log/aurora.log
EOF
    
    # Install systemd service (if applicable)
    if [ -d "/etc/systemd/system" ] && [ "$EUID" -eq 0 ]; then
        echo "  Installing systemd service..."
        cat > /etc/systemd/system/aurora.service << EOF
[Unit]
Description=AURORA Compute Runtime
After=network.target

[Service]
Type=simple
ExecStart=$PREFIX/bin/aurora daemon
Restart=on-failure
User=root

[Install]
WantedBy=multi-user.target
EOF
        systemctl daemon-reload 2>/dev/null || true
    fi
    
    # Create environment setup script
    echo "  Creating environment script..."
    cat > "$PREFIX/bin/aurora-env.sh" << EOF
#!/bin/bash
# AURORA Environment Setup

export AURORA_HOME="$PREFIX"
export PATH="$PREFIX/bin:\$PATH"
export LD_LIBRARY_PATH="$PREFIX/lib:\$LD_LIBRARY_PATH"

# Load configuration if exists
if [ -f "$PREFIX/etc/aurora.conf" ]; then
    export AURORA_CONFIG="$PREFIX/etc/aurora.conf"
fi

echo "AURORA environment configured."
echo "Version: \$(aurora version 2>/dev/null || echo 'unknown')"
EOF
    chmod +x "$PREFIX/bin/aurora-env.sh"
    
    echo -e "  ${GREEN}✓${NC} Installation complete"
    echo ""
}

# Install kernel modules
install_kernel_modules() {
    if [ "$INSTALL_KERNEL" = false ]; then
        return
    fi
    
    echo -e "${BLUE}Installing kernel modules...${NC}"
    
    if [ "$EUID" -ne 0 ]; then
        echo -e "${YELLOW}Warning: Kernel module installation requires root privileges${NC}"
        return
    fi
    
    # Check kernel headers
    if [ ! -d "/lib/modules/$(uname -r)/build" ]; then
        echo -e "${YELLOW}Warning: Kernel headers not found. Skipping kernel modules.${NC}"
        return
    fi
    
    echo "  Building kernel modules..."
    # Would build kernel modules here
    
    echo "  Installing kernel modules..."
    # Would install kernel modules here
    
    echo -e "  ${GREEN}✓${NC} Kernel modules installed"
    echo ""
}

# Tune system for performance
tune_system() {
    if [ "$TUNE_SYSTEM" = false ]; then
        return
    fi
    
    echo -e "${BLUE}Tuning system for optimal performance...${NC}"
    
    if [ "$EUID" -ne 0 ]; then
        echo -e "${YELLOW}Warning: System tuning requires root privileges${NC}"
        return
    fi
    
    # Set CPU governor to performance
    echo "  Setting CPU governor to performance..."
    if command -v cpufreq-set &> /dev/null; then
        for cpu in /sys/devices/system/cpu/cpu[0-9]*; do
            cpufreq-set -c "$(basename "$cpu" | sed 's/cpu//')" -g performance 2>/dev/null || true
        done
    fi
    
    # Enable HugePages
    echo "  Enabling HugePages..."
    echo 128 > /proc/sys/vm/nr_hugepages 2>/dev/null || true
    
    # Set swappiness
    echo "  Setting vm.swappiness to 10..."
    echo 10 > /proc/sys/vm/swappiness 2>/dev/null || true
    
    # Disable transparent hugepage defragmentation
    echo "  Configuring Transparent HugePages..."
    echo never > /sys/kernel/mm/transparent_hugepage/defrag 2>/dev/null || true
    
    # Increase file descriptor limits
    echo "  Increasing file descriptor limits..."
    echo '* soft nofile 65536' >> /etc/security/limits.conf 2>/dev/null || true
    echo '* hard nofile 65536' >> /etc/security/limits.conf 2>/dev/null || true
    
    echo -e "  ${GREEN}✓${NC} System tuned"
    echo ""
}

# Create symlinks
create_symlinks() {
    echo -e "${BLUE}Creating symlinks...${NC}"
    
    if [ "$EUID" -eq 0 ]; then
        # System-wide installation
        if [ -d "/usr/local/bin" ]; then
            ln -sf "$PREFIX/bin/aurora" /usr/local/bin/aurora 2>/dev/null || true
            echo -e "  ${GREEN}✓${NC} Created /usr/local/bin/aurora"
        fi
    fi
    
    echo ""
}

# Print completion message
print_completion() {
    echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}  AURORA installed successfully!${NC}"
    echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
    echo ""
    echo "Installation directory: $PREFIX"
    echo ""
    echo "To use AURORA, add to your shell profile:"
    echo "  source $PREFIX/bin/aurora-env.sh"
    echo ""
    echo "Or manually add to PATH:"
    echo "  export PATH=$PREFIX/bin:\$PATH"
    echo ""
    echo "Get started:"
    echo "  aurora detect    # Detect hardware"
    echo "  aurora benchmark # Run benchmarks"
    echo "  aurora --help    # Show all commands"
    echo ""
    
    if [ "$TUNE_SYSTEM" = true ]; then
        echo -e "${YELLOW}Note: System tuning has been applied.${NC}"
        echo "Some changes may require a reboot to take full effect."
        echo ""
    fi
}

# Main installation
main() {
    print_banner
    
    check_prerequisites
    build_aurora
    install_files
    install_kernel_modules
    tune_system
    create_symlinks
    print_completion
}

# Run main
main "$@"
